### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by neelkamath** [blenderskool/blaze#1]
I ran the README instructions but didn't know where the server or whatever was. And I'm not sure whether this is like a SHAREit competitor where I needn't install an app to use it and such, so maybe state reasons as to why this was made (e.g., just for fun or for actual use).

**Comment by blenderskool** [comment]
Commit is on the way. This project is very new on GitHub

**Comment by blenderskool** [comment]
@neelkamath Commit pushed.
