### ISSUE TITLE
docker-compose fails at prerender

### ISSUE THREAD

**Issue by lilmike** [blenderskool/blaze#108]
I get an error in blaze-client when running docker-compose up -d output:

<pre>
Step 16/20 : RUN npm run build
 ---> Running in 891660796c3a

> blaze-frontend@2.1.1 build /app/client
> preact build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

 ssr-bundle.e1978.css ■  4.12 kB (+4.12 kB)
        ssr-bundle.js ■  30.6 kB (+30.6 kB)

   ssr-bundle.e1978.css ■  0 B (-4.12 kB)
          ssr-bundle.js ■  0 B (-30.6 kB)
       bundle.5f534.css ■  4.04 kB (+4.04 kB)
    bundle.*****.esm.js ■  33.8 kB (+33.8 kB)
 polyfills.*****.esm.js ■  2.02 kB (+2.02 kB)
                  sw.js ■  10.6 kB (+10.6 kB)
              sw-esm.js ■  10.6 kB (+10.6 kB)
        bundle.fc54b.js ■  34.5 kB (+34.5 kB)
     polyfills.694cb.js ■  2.01 kB (+2.01 kB)

ReferenceError: window is not defined
method: os/r
at: /app/client/src/utils/urls.js:5:8

Source code:

export default {
  WS_HOST: (() => {
    if (WS_HOST) return WS_HOST;
    if (window.location.protocol === 'https:') {
      return `wss://${window.location.host}/ws`;
    } else {
      return `ws://${window.location.host}/ws`;
    }

This is most likely caused by using DOM or Web APIs.
Pre-render runs in node and has no access to globals available in browsers.

Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'

Alternatively use 'preact build --no-prerender' to disable prerendering.

See https://github.com/developit/preact-cli#pre-rendering for further information.npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! blaze-frontend@2.1.1 build: `preact build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the blaze-frontend@2.1.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-21T14_52_57_033Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
ERROR: Service 'blaze-client' failed to build
</pre>

Thanks!
-Michael.

**Comment by blenderskool** [comment]
Seems like this is also causing the docker builds on Docker Hub to also fail. Interestingly the normal builds of the frontend go through fine separately.

**Comment by sunrisepi** [comment]
Hi @lilmike  and @blenderskool , I figured out how to get this to build via **docker-compose up -d**.  All you need to do is observe what is shown in the above error output:
```
[...]
Alternatively use 'preact build --no-prerender' to disable prerendering.
[....]
```
So, I edited **blaze/client/package.json**, updating the line **preact build** in the section at the top, so it matches what is shown in the above error excerpt:

> {
>   "name": "blaze-frontend",
>   "version": "2.1.1",
>   "description": "Quickly share files with multiple users",
>   "private": true,
>   "scripts": {
>     "dev": "preact watch",
>     **"build": "preact build --no-prerender",**
>     "start": "sirv build --cors --single --port 8080",
>     "lint": "eslint src"
>   },
> 

After making that change, run **docker-compose up -d** and it should complete fine.  I tested this on my 32-bit Raspberry Pi 4B (ARM processing power 😄!!!) and it seemed to work without any issues.   It would be nice to have prerendering support, but it doesn't seem to be mandatory.

BTW @blenderskool, very nice work!  The app you created looks very professional, beautiful and elegant.  👏

**Comment by blenderskool** [comment]
Thank you @sunrisepi! 😄

We actually need prerendering support as it helps with SEO. I think right now only the home page and how it works page are prerendered. There's no need to prerender the app page as it is just a shell and not really static.

**Comment by sunrisepi** [comment]
Thanks for the info @blenderskool!  If we wish to try to get docker to build the image with prerendering support, you may have noticed it mentioned this in the error output @lilmike shared:

`Consider wrapping code producing error in: 'if (typeof window !== "undefined") { ... }'`

I just wanted a quick way to get the image to build.  I did notice without prerendering support, that when first loading the homepage you see some "staging content".  I am not sure how to explain it.  Basically you can almost see the web content being constructed.. then a half second later you see the homepage rendered the way it should be, very pretty and beautiful. 

So yes, prerendering support makes things look better.  Thank you!

**Comment by blenderskool** [comment]
@sunrisepi Interesting behaviour, will look into this more.

As per the issue, I haven't been able to give time to look into this. If anyone more familiar with Docker can try fixing this, would be a great help 🙂
