### ISSUE TITLE
WebRTC not working across different networks

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#11]
WebRTC works when the clients are in same network, but fails (switches to WebSockets) when they are in different networks.

**Comment by blenderskool** [comment]
This is most likely because there is no TURN server being used.

**Comment by RotonEvan** [comment]
> This is most likely because there is no TURN server being used.

Yeah that's one possibility. Second is ICE fails a lot in firefox. Do you possibly use firefox?

**Comment by blenderskool** [comment]
@RotonEvan No not using Firefox right now

**Comment by elearningdienst** [comment]
Can I use a TURN server within blaze? I have coturn up and running as my nextcloud talk module needs a TURN server for compatibility reasons.

**Comment by blenderskool** [comment]
@elearningdienst Yes it is possible to use a coturn server with Blaze. You'll have to add your TURN server details to this file, and rebuild Blaze client app https://github.com/blenderskool/blaze/blob/61998dd02bd1d47d011f1ce6ace0a2c9747cbf63/client/src/utils/fileShare.js#L17

**Comment by blenderskool** [comment]
Closing this as this is not a problem with Blaze. To ensure WebRTC works across all networks, a TURN server needs to be configured which can be done using [coturn](https://github.com/coturn/coturn) in case anyone is interested in self-hosting.
