### ISSUE TITLE
Error while creating a room

### ISSUE THREAD

**Issue by mishailovic** [blenderskool/blaze#111]
When I create a room, nothing happens, and I also cannot join the room. I've tried using vpn and incognito mode, it doesn't help. The same problem is happening on the phone.

**Comment by blenderskool** [comment]
Which browser? And which browser version?

**Comment by mishailovic** [comment]
latest version of chrome

**Comment by blenderskool** [comment]
@mishailovic Fixed this. Seems like Vercel deprecated the use of `now.sh` domains and they now redirect to `vercel.app`. Things should be working as before.

**Comment by mishailovic** [comment]
👍
