### ISSUE TITLE
Progress Indicator and direct links

### ISSUE THREAD

**Issue by Chaitanyap22** [blenderskool/blaze#114]
1. (Feature Request) Please add progress indicator to the sender side too, I think its really important as receiver can't always update the sender the percentage of file sent. It will be great if you could add this.

2. (Bug Fix / App Enhancement) I don't know whether it is a feature or bug, whenever you open the app and directly type /app/t/{block name} in address bar of the web browser then block is created directly, which sets the host unknown. App need the capability to block those direct links.

**Comment by blenderskool** [comment]
> 1. (Feature Request) Please add progress indicator to the sender side too, I think its really important as receiver can't always update the sender the percentage of file sent. It will be great if you could add this.

This might be tricky, as a sender can be simultaneously sharing files to multiple users making the progress % different for different peers. I don't think WebTorrent natively calculates upload progress for the same. Will think over it again though if it's possible here.

> 2. (Bug Fix / App Enhancement) I don't know whether it is a feature or bug, whenever you open the app and directly type /app/t/{block name} in address bar of the web browser then block is created directly, which sets the host unknown. App need the capability to block those direct links.

This is a feature, although I don't fully understand what you mean by "sets the host unknown". All users should specify a name before joining any room whether it's through direct links or from the app.
Speaking of direct links, any reason why you'd want to block direct links?

**Comment by Chaitanyap22** [comment]
Blocking direct links will force user to create link through start sharing button, this will make needful element like donate button more visible to the users and can generate more revenue. 


Forgot to mention 3rd point to mention 😅

If the app is opened on a single device but using multiple browsers, then same device appears as different users. I think even this should be blocked as user won't share files to himself unless there are 2 different devices.

**Comment by blenderskool** [comment]
Blocking direct links would also add friction to users who receive **links to join a room**. They will be stuck on Rooms page where they'll have to click on `New Room` and type the name of the room they wanted to join.

If donations are the main concern, we can add a non-obtrusive donation button in the file transfer page as well :smile: 

> If the app is opened on a single device but using multiple browsers, then same device appears as different users. I think even this should be blocked as user won't share files to himself unless there are 2 different devices.

This I don't think Blaze should handle. If the user knows that they have joined the same room with the same device but different browsers, they probably did it for some reason. The effort required to add this extra logic and keep track of device ids will outweigh the benefits.

**Comment by blenderskool** [comment]
Closed via 1f5655da63537c8676c3900f2919d651da2e1fc7
