### ISSUE TITLE
why sometimes intermediary server + file size limit + transfer speeds very slow ?

### ISSUE THREAD

**Issue by ihubgit** [blenderskool/blaze#120]
Hi, both peers are on a different 4G mobile network. They mostly manage to establish a direct p2p connection, but transfer speeds are _always_ very slow. Why ? 
Why on other occasions (still the same 4G networks) there's a need for an intermediary server and when this is the case, why is the file size capped to like 93 Mb ?

**Comment by blenderskool** [comment]
Hi @ihubgit,

> both peers are on a different 4G mobile network. They mostly manage to establish a direct p2p connection, but transfer speeds are always very slow. Why ?

Transferring over direct p2p connection utilizes WebTorrent. Following 2 things can cause slow transfer speeds from what I have noticed:
- _very large_ files, preparing a torrent out of them and seeding it takes a considerable about of time. (Even more, if the device does not have large computing power)
- Perhaps the P2P connection was facilitated via the TURN server, which may cause slower than usual speeds? (I don't have any evidence for this though)

> Why on other occasions (still the same 4G networks) there's a need for an intermediary server and when this is the case, why is the file size capped to like 93 Mb ?

An intermediary server is used to transfer files when some device **does not support WebRTC or has it disabled**. This intermediary server uses WebSockets to transfer files. Without this fallback, Blaze would simply not work and lead to a bad experience for users who aren't familiar with how to enable WebRTC.  
The file size is capped to 93 Mb as WebSockets consumes server bandwidth, and large file transfers would lead to high bandwidth costs. However, if you were to host Blaze on your own server, you can increase these limits as per your needs.

Hope that helps :slightly_smiling_face:

**Comment by blenderskool** [comment]
Closing this, open again if there are further questions in this.
