### ISSUE TITLE
Displaying QR code of instant room for easier access

### ISSUE THREAD

**Issue by japoodev** [blenderskool/blaze#126]
I am a frequent user of this project and really love the product. This is a small feature suggestion. When an instant room is created, along with the "copy room link" button, a QR code of the link below that will make accessing the room from smartphone faster and more streamlined

**Comment by blenderskool** [comment]
@japoodev Glad to here that you like this project 😄

Yep, this feature makes sense. I think default QR code scanner on phones would suffice right? Blaze can only handle generating the QR code 🙂

**Comment by blenderskool** [comment]
Closed via d92e39e4010249944204fc1d32f3912f9e9e5e75
