### ISSUE TITLE
Local synchronization and communication

### ISSUE THREAD

**Issue by vkkhare** [blenderskool/blaze#127]
Really love Blaze for the time I have used.

Why not share the files over local connections if available like Bluetooth, wifi, wifi-p2p. This will remove the necessity to have internet or even wifi. There is no integrated solution at present, I think Blaze can do that.

There are some open-source implementations available for local device discovery, network management. We can use those!

**Comment by blenderskool** [comment]
@vkkhare I'm not sure if this is possible right now directly with JavaScript on the browser. The closest thing to P2P is WebRTC but that would also need a signaling server for establishing a P2P connection.

Can you share the open-source implementations you found here for reference, would check them out 🙂

**Comment by vkkhare** [comment]
We found some projects that are integrating these local communication mediums https://github.com/project-chip/connectedhomeip. We ourselves are building one that supports a unified interface for the libs (so they don't need to worry about it) specifically focussed on cross-compatibility

If this seems like a nice idea maybe we can discuss how to integrate it?

**Comment by blenderskool** [comment]
@vkkhare Interesting stuff. Would be great to know more about this.

By the way, is the medium y'all working on designed to work on the browsers? Would be interesting to check it out.

**Comment by vkkhare** [comment]
One of our core focus is to support communication between browsers and native apps. At present, we are starting with supporting wifi with Bluetooth and expand into other protocols. The stack does device discovery and network management for the end-developer and as mentioned will be open-sourced.

Let's discuss over [slack](https://join.slack.com/t/nimbleedgecommunity/shared_invite/zt-ry422epv-~uJg4azOlFl2zSy6EiFSnA). Keen on taking your feedback.
