### ISSUE TITLE
PWA Shortcut to join Instant room

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#133]
Using [PWA App shortcuts API](https://web.dev/app-shortcuts/), a shortcut to joining an instant room can be added. Clicking on this shortcut would take the user directly to the newly created instant room skipping the recent rooms page.

**Comment by yash-jain24** [comment]
can i work on it?

**Comment by blenderskool** [comment]
@gVirtu Sure, please go ahead. As for the icon, yes, we can have the same icon as the one shown in the room's creation modal. I have attached the icon for this below. Do let me know if you need anything else.

[instant_room_shortcut_icon.png](https://user-images.githubusercontent.com/21107799/137638423-2a7aaf40-820d-432b-b688-bfe746a91f44.png)

**Comment by blenderskool** [comment]
Closed via #134
