### ISSUE TITLE
NGINX Reverse Proxy

### ISSUE THREAD

**Issue by elearningdienst** [blenderskool/blaze#135]
Hi Folks, 

I have only one public IPv4. Is it possible to use an nginx proxy on an other server than the machine wich the docker image is on?

Greetings from Germany

**Comment by blenderskool** [comment]
Yes, I think this should be possible, you could proxy the requests from the public server to the other server's IP address and port number using nginx.

Let me know if I understood it incorrectly.

**Comment by elearningdienst** [comment]
Can I use a TURN server within blaze? I have coturn up and running as my nextcloud talk module needs a TURN server for compatibility reasons.

**Comment by elearningdienst** [comment]
Seems to work, but (as on your own instance) it is only possible to share files in the same network.

**Comment by elearningdienst** [comment]
Does not work as expectet, the fallback to websocket seems not to work. Here is the reverseproxy config part I usually use:

`   location / {
      proxy_pass http://___internalip_____:___port____;
      proxy_redirect off;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Protocol $scheme;
      proxy_set_header X-Url-Scheme $scheme;
      proxy_read_timeout 1200s;
      proxy_http_version 1.1;
      proxy_set_header Accept-Encoding "";
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_cache_bypass $http_upgrade;
      proxy_set_header X-Real-IP $remote_addr;

}
`

Website works, sharing within my network works. If one ore more clients are outside the network, the fallback to websocket fails (I think). Any Ideas how to debug that?

**Comment by blenderskool** [comment]
Not sure if this was resolved, but for anyone facing this issue, please refer [this](https://github.com/blenderskool/blaze/blob/master/nginx/image-nginx.template) nginx config to setup the proxy correctly.
Also, if WebRTC fails to work across networks, consider setting up your own TURN server using something like [coturn](https://github.com/coturn/coturn) and add the URL of the TURN server here
https://github.com/blenderskool/blaze/blob/master/client/src/utils/fileShare.js#L17-L24

After the URL has been added, rebuild and redeploy the client web app.

**Comment by blenderskool** [comment]
Assuming it was resolved.
