### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 429

### ISSUE THREAD

**Issue by studynetskill** [blenderskool/blaze#137]
I have encountered some problems. When I transfer files from the computer to the mobile phone, it is successful, but when I transfer files from the mobile phone to the computer, there are errors. The errors are as follows：

webtorrent.min.js:6 
        
       WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 429
Socket @ webtorrent.min.js:6
_openSocket @ webtorrent.min.js:1
WebSocketTracker @ webtorrent.min.js:1
(匿名) @ webtorrent.min.js:1
Client @ webtorrent.min.js:1
_createTracker @ webtorrent.min.js:6
Discovery @ webtorrent.min.js:6
_startDiscovery @ webtorrent.min.js:1
_onListening @ webtorrent.min.js:1
_onParsedTorrent @ webtorrent.min.js:1
(匿名) @ webtorrent.min.js:1
Item.run @ webtorrent.min.js:6
drainQueue @ webtorrent.min.js:6
teeny-stove-2909:4 
        
       GET https://github.com/blenderskool.png?size=100 net::ERR_CONNECTION_RESET
teeny-stove-2909:4 
        
       GET https://opensource.nyc3.cdn.digitaloceanspaces.com/attribution/assets/PoweredByDO/DO_Powered_by_Badge_white.svg net::ERR_CONNECTION_CLOSED
webtorrent.min.js:6 
        
       WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 429
Socket @ webtorrent.min.js:6
_openSocket @ webtorrent.min.js:1
(匿名) @ webtorrent.min.js:1
webtorrent.min.js:6 
        
       WebSocket connection to 'wss://tracker.openwebtorrent.com/' failed: Error during WebSocket handshake: Unexpected response code: 429

**Comment by blenderskool** [comment]
Odd errors. Could be some firewall issue.
Can you share more details about the error?
- Browser Name
- Browser version
- Where did the above errors occurr? Computer or Phone.

**Comment by blenderskool** [comment]
Closing as there have been no updates from the OP.
