### ISSUE TITLE
PLS remove node-sass

### ISSUE THREAD

**Issue by williamyan1024** [blenderskool/blaze#139]
PLS remove node-sass :)

**Comment by blenderskool** [comment]
@williamyan1024 Any reason why it should be removed?

**Comment by williamyan1024** [comment]
node-sass low-level dependencies [libsass](https://github.com/sass/libsass), resulting in many users installing Especially difficult for Windows users, it forces users to install python2 and Visual Studio in the windows environment to compile successfully.

**Comment by blenderskool** [comment]
@williamyan1024 Oh. Any alternatives that you'd suggest? I also noticed that `node-sass` is now deprecated.

**Comment by blenderskool** [comment]
`node-sass` has been replaced by `sass` package
