### ISSUE TITLE
small css fix needed on "join an instant room" button on mobile devices

### ISSUE THREAD

**Issue by csahu3008** [blenderskool/blaze#147]
![Screenshot_2022-08-28-14-06-53-47_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/43113942/187070829-3027840a-613c-4b26-8a85-dac3018d0b46.jpg)

small css fix needed on "join an instant room" button on mobile devices while joining a new room

**Comment by blenderskool** [comment]
Maybe rephrasing it to "Join Instant Room" fit.

**Comment by ethAmazinDor** [comment]
hey is this still open ?

**Comment by blenderskool** [comment]
@ethAmazinDor Yes

**Comment by Medmly20208** [comment]
hey I opened a pull request to solve this problem check it out

**Comment by blenderskool** [comment]
Closed via #148
