### ISSUE TITLE
Update version of WebTorrent library

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#150]
Blaze currently uses WebTorrent v0.108.6 script. We should update it to the more recent versions.

To anyone who's interested in picking this up, make sure to:
- Check if the new versions of WebTorrent (v1.x) are backward compatible with v0.x versions (that Blaze uses currently).
- Check if file sharing works as expected after the upgrade.
- Add a comment here if any breaking change of WebTorrent library requires changes in the Blaze codebase as well.

**Comment by AndrewDineen** [comment]
Hi, can I take this issue?

**Comment by blenderskool** [comment]
@AndrewDineen Sure please go ahead!

**Comment by blenderskool** [comment]
@AndrewDineen Are you still working on this? Any updates?

**Comment by blenderskool** [comment]
Closed via dba713f3fcc43c4b9247fad470b2d576ec83466d
