### ISSUE TITLE
Update design of onboarding screen

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#151]
The current onboarding screen only shows an input field to choose a nickname.
New design can include some more context as to what nicknames do in Blaze.

**Comment by g4m3r0** [comment]
Hey @blenderskool, I would like to work on this issue.
The project is very nice!

Do you already have something specific in mind that should be shown?
Just a message what the nickname is used for?

**Comment by blenderskool** [comment]
@g4m3r0 Thanks for taking interest in Blaze!
You can find a rough design of what I'm thinking of here https://www.figma.com/file/C0jhaGi2zBgswsOlOhVuWa/Blaze---file-sharing?node-id=0%3A1

I'm not sure which one's better between `Mobile 1` and `Mobile 2` right now, will be able to go ahead with one once I try both on an actual device. Since both are similar in terms of layout, I think it shouldn't be hard to modify one to look like the other one.

Do let me know your thoughts / suggestions.

**Comment by g4m3r0** [comment]
@blenderskool that design looks fantastic.
Personally, I would prefer `Mobile 1` because it looks cleaner and more "natural" to me.
But yeah that look and feel indeed depends on the screen resolution of the device.

**Comment by blenderskool** [comment]
@g4m3r0 Are you working on this?

**Comment by blenderskool** [comment]
Closed via 2a32ff34cbf171d76cf327008e4a4a01d1e85bb8
