### ISSUE TITLE
how to start server with pm2？

### ISSUE THREAD

**Issue by kainy** [blenderskool/blaze#162]
when I start with pm2 ，it come with error：

`SyntaxError: Unexpected token ':'                                        ││                                  ││ blaze >     at Object.compileFunction (node:vm:352:18)                           ││                                  ││ blaze >     at wrapSafe (node:internal/modules/cjs/loader:1033:15)               ││                                  ││ blaze >     at Module._compile (node:internal/modules/cjs/loader:1069:27)        ││                                  ││ blaze >     at Object.Module._extensions..js (node:internal/modules/cjs/loader:  ││                                  ││ blaze >     at Module.load (node:internal/modules/cjs/loader:981:32)             ││                                  ││ blaze >     at Function.Module._load (node:internal/modules/cjs/loader:822:12)   ││                                  ││ blaze >     at Object.<anonymous> (C:\Users\guotao\AppData\Roaming\npm\node_mod  `

has any one use blaze whit pm2，thanks。

**Comment by blenderskool** [comment]
Check the following:
- Node.js version – v16.x is currently supported.
- Installed all dependencies at _root of the project_ by running `npm install`.
- In `server` directory, create a `ecosystem.config.js` file with following configuration:

   ```js
     module.exports = {
      apps : [{
        script: 'npm -- start',
        watch: '.',
        env: {
          "NODE_ENV": "production",
           // rest of the env variables for the server here...
        }
      }],
    };
   ```
- Run `pm2 start` in the `server` directory.
