### ISSUE TITLE
Base url setting for reverse proxy 

### ISSUE THREAD

**Issue by echo-saurav** [blenderskool/blaze#166]
Can anyone add base url setting like `domain/blaze`

**Comment by blenderskool** [comment]
@echo-saurav Sorry, I didn't understand

**Comment by blenderskool** [comment]
Closing as there is no update. Please reopen if you have any more questions / things to be solved.

**Comment by sonyarianto** [comment]
Means install blaze on base path situation. If we install blaze on let say blaze.domain.com it's fine, but if we install domain.com/blaze then seems blaze not aware of base path (which is the blaze is the base path here)

**Comment by blenderskool** [comment]
@sonyarianto Hmm I see, I'll try it out when I get some time but I feel it shouldn't be a problem as you can pass the env variables listed at https://github.com/blenderskool/blaze#build-process with correct paths to your deployment.
