### ISSUE TITLE
Running blaze behind Nginx Reverse Proxy

### ISSUE THREAD

**Issue by SomeCodecat** [blenderskool/blaze#169]
I wanted to know whether it would be possible to run Blaze behind Nginx Reverse Proxy.
My problem is that I cannot establish a peer to peer connection with that.
I can see the Frontend but the server does not even get any requests when i view the logs.

TL:DR
Can I run Blaze behind Nginx Reverse Proxy?
If yes, how?

**Comment by blenderskool** [comment]
@SomeCodecat Yes, you can use Nginx reverse proxy for Blaze. It's also a part of the Blaze docker images and you can check the configurations they use for reference here https://github.com/blenderskool/blaze/tree/master/nginx incase you missed some rule

Do note that enabling websocket connections with server  behind Nginx proxy require additional configuration, which again is available in the files linked above.

**Comment by blenderskool** [comment]
Closing as there is no update. Please reopen if you have any more questions.
