### ISSUE TITLE
docker container not starting

### ISSUE THREAD

**Issue by klmbrgr** [blenderskool/blaze#173]
Hi 👋
I was hoping you  can help me on, getting the docker container started. I haven an openmediavault environment running. After creating a new stack (copy / paste the docker compose yml) and starting it up, I get following error:

`OMV\ExecException: Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; docker compose --file '<my-server-path>/docker-compose/blaze/blaze.yml' --env-file '<my-server-path>/docker-compose/blaze/blaze.env' --env-file '<my-server-path>/docker-compose/global.env' up -d 2>&1': could not find <my-server-path>/docker-compose/blaze/server: stat <my-server-path>/docker-compose/blaze/server: no such file or directory in /usr/share/openmediavault/engined/rpc/compose.inc:613`

What do I need to cover in addition?

Thanks guys.

**Comment by blenderskool** [comment]
It seems like you haven't cloned the project. You have to clone the project in `master` branch and then run docker compose. Copy-pasting only the compose file won't work since the compose file references other local Dockerfiles and NGINX configs

**Comment by klmbrgr** [comment]
@blenderskool thank you for your explanation. I guess, this is yet beyond my knowledge, what it means to clone a master branch. Too bad, as it seemed like blaze was the solution to go for me, compared to the other P2P file sharing solutions, which are no solution for my use case.
But thanks a lot for your time to respond anyway :)

**Comment by blenderskool** [comment]
@kolmberger Its not very hard to clone the project. Cloning simply means taking a copy of the source code of the project on your system. You can use the following command to clone blaze:
```sh
git clone https://github.com/blenderskool/blaze
cd blaze
```

Then run docker compose:
```sh
docker-compose up
```

Hope this helps in clearing some confusion you might have :)

**Comment by blenderskool** [comment]
Closing as it's answered and there's no further activity.
