### ISSUE TITLE
Add settings page

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#25]
A settings page can be used to allow to edit nicknames and other details of the client.

**Comment by blenderskool** [comment]
@alceil There are no designs for this page yet, will work on this once we finalize the options which will be shown on this page. Then maybe it'll be easier for you to work on it.
As of now:
- changing nickname

If you have any suggestions for this page, please share 🙂

**Comment by alceil** [comment]
Okay cool

**Comment by blenderskool** [comment]
✅ Closed via e5b958e120c8d74c8d34d3843fd728b97811f9c1
