### ISSUE TITLE
Prevent rooms with reserved symbols

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#38]
While joining a new room, the room name must not contain characters such as `#, ?, & ...` which have a special meaning in a URL. When these characters are used, the app stops working as expected.

Hence the room name must be validated to prevent reserved symbols.

**Comment by skywalkerluc** [comment]
May I take this?

**Comment by blenderskool** [comment]
Sure @skywalkerluc :slightly_smiling_face: 

I will be adding contribution guidelines(#39) for this project soon!

**Comment by skywalkerluc** [comment]
Should I avoid special characteres showing on input or validate after submit (using pattern attr)?

**Comment by skywalkerluc** [comment]
I mean, if I just use pattern attr, after clicking "Join Room", a tooltip will appear bellow saying: "Please match the requested format".

**Comment by blenderskool** [comment]
`pattern` attribute should be fine. We can try showing a custom tooltip when the validation fails.
