### ISSUE TITLE
A new identity for Blaze ⚡

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#66]
Blaze is built for sharing files across multiple peers in a _blazing-fast_ way. While the current logo mainly featured a cloud with a lightning symbol, it did not capture the true identity of Blaze.

### New logo proposal
The new logo tries to improve upon the current logo of Blaze by retaining the original colors and the lightning symbol.
- The cloud is dropped completely as Blaze is primarily meant to be a *peer-to-peer* tool and keep very minimal dependency on central server. For the file sharing case, a cloud may have an incorrect perception as a cloud storage solution(which Blaze isn't)

- The lightning symbol is now the primary part of the logo as it correctly captures the speed and ease of use Blaze tries to achieve. The design of the lightning symbol is updated to look similar to the zap emoji :zap: which is mostly used for referencing Blaze in articles and posts.

- Small dots have been added on the lightning symbol to indicate peers connected to each other. The lightning here can also be interpreted as a _medium_ to connect peers with each other.

- The text gets a new look from the [Jost font](https://fonts.google.com/specimen/Jost) family. This font change was recently made on the app.

#### Logo with the text
<img src="https://user-images.githubusercontent.com/21107799/89798625-079cc980-db4a-11ea-8d93-4816e27e89aa.png" width="300">

#### Logo as an app icon
<img src="https://user-images.githubusercontent.com/21107799/89800300-39169480-db4c-11ea-92ac-96258bc44722.png" width="192">

#### Logo on installed PWA
<img src="https://user-images.githubusercontent.com/21107799/89800768-d40f6e80-db4c-11ea-801c-637c8e882ca1.png" width="400">

**Comment by prediscover** [comment]
Looks nice! Love the theme
