### ISSUE TITLE
When sharing among 3 users 2 users in chrome 1 user on safari 

### ISSUE THREAD

**Issue by vishalveerareddy** [blenderskool/blaze#68]
File transfer is stuck forever 
when I close the safari user the room is blocked.

**Comment by blenderskool** [comment]
@vishalveerareddy Which branch was this tested on? `master` or `next`?

**Comment by vishalveerareddy** [comment]
master

**Comment by blenderskool** [comment]
Closing this issue as it was solved in v2.0.0 and does not occur anymore
