### ISSUE TITLE
Update document title when joining a room

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#73]
Joining a room does not change the document title and it remains `App | Blaze`.
After joining the room (in `FileTransfer.js`), title should become `<room-name> room | Blaze`, and should change back to `App | Blaze` on when returning back to Rooms page.

**Comment by OmkarPh** [comment]
I look forward to work on this issue, can you assign it to me.

**Comment by blenderskool** [comment]
Sure @OmkarPh 🙂
