### ISSUE TITLE
Fix share target capturing text as shared.txt file

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#74]
The web share target (defined in `client/src/manifest.json`) currently accepts only files, but some apps share some text data with files. Example: "This file was created with [App name] [App URL]".

Right now the share target takes the text data and creates a file out of it called `shared.txt` and then gets transferred via Blaze.
This is annoying for some users as this data is **not really useful in file sharing and serves no real purpose.**

A fix for this is to update the definition of share target with a field that would accept the text data. This would prevent the text data from becoming the `shared.txt` file and getting transferred.

References:
- https://web.dev/web-share-target/#accepting-files

**Comment by abhishek-aa** [comment]
@blenderskool I think this can be fixed by adding 'text' and 'title' under 'params' in manifest.json.

**Comment by cristicismas** [comment]
I could make a quick PR if you assign me. So, all I would need to do is add the `text` and `title` under `params` in `manifest.json`? If so, what should these values be? I don't have a lot of experience with PWAs.

**Comment by blenderskool** [comment]
@abhishek-aa Yes it may be fixed with those additions.

@cristicismas We are not reading the value of `text` or `title` in the service worker right now so it can technically be anything. Maybe keep something short and simple in case we need it later.
