### ISSUE TITLE
Show copy link button when web share API is unavailable

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#75]
Since some browsers don't support web share API (which is shown on mobiles to share the link to Blaze room), a copy link button can be shown in its place which would copy the link to the clipboard.

We can make use of [copy-to-clipboard](https://www.npmjs.com/package/copy-to-clipboard) package for this.

For reference, on mobiles, this is the share button.
<img src="https://user-images.githubusercontent.com/21107799/94659433-e4a8bd80-0321-11eb-8219-16f3b5ced71f.png" width="300">

**Comment by OmkarPh** [comment]
I am interested to work on this issue.

**Comment by abhishek-aa** [comment]
I would like to work on this issue. I have worked on WebSockets and WebRTC and I can easily get this done. Please provide me a chance to work on this issue and I'll deliver the results as soon as possible!

**Comment by blenderskool** [comment]
@OmkarPh Sure go ahead.

@abhishek-aa Not going to stop you from working on this, but since you have worked with WebSockets and WebRTC maybe you can checkout other issues involving these concepts :slightly_smiling_face:

**Comment by OmkarPh** [comment]
@abhishek-aa  you can do the work faster than me, I think you should do it, 
I am currently working on something else anyways, I would like to see your approach and it would be great to know something new, if you couldn't then I'll definitely give a try  :)

**Comment by abhishek-aa** [comment]
@blenderskool Sure! I'll checkout other issues as well!

**Comment by abhishek-aa** [comment]
Please assign me this issue. I have already created a pull request.
