### ISSUE TITLE
CONTRIBUTING.md Project setup issue

### ISSUE THREAD

**Issue by abhishek-aa** [blenderskool/blaze#79]
Under project setup, the steps mentioned are out of order. According to me, 'cd blaze' command must come before 'git remote add upstream https://github.com/blenderskool/blaze.git'.

**Comment by abhishek-aa** [comment]
I am working on another open issue so I can fix this bug. Please assign me this issue and I will submit the PR including the fix for both the issues.

**Comment by blenderskool** [comment]
@abhishek-aa Yes, seems like I missed it while writing the contributing guide. You can work on fixing it :slightly_smiling_face:

**Comment by abhishek-aa** [comment]
@blenderskool Correct me if I'm wrong, shouldn't ```bash
git checkout -b my-branch next
```
be ```bash
git checkout -b my-branch origin/next
```
?

**Comment by abhishek-aa** [comment]
@blenderskool

**Comment by blenderskool** [comment]
> @blenderskool Correct me if I'm wrong, shouldn't
> 
> ```shell
> git checkout -b my-branch next
> ```
> 
> be
> 
> ```shell
> git checkout -b my-branch origin/next
> ```
> 
> ?

Doesn't really matter for new users who are following the CONTRIBUTING guide as the local `next` and `origin/next` branches would be the same for the first time.

**Comment by abhishek-aa** [comment]
@blenderskool I think that's where the issue is....there is no local ```next``` when someone starts working.

**Comment by abhishek-aa** [comment]
created a pull request. Please review and merge!
