### ISSUE TITLE
Fix basic accessibility issues

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#82]
There are some basic accessibility issues on the landing page of Blaze which can be seen on Lighthouse.

![image](https://user-images.githubusercontent.com/21107799/95023140-f29b6d00-0698-11eb-80c0-c9be2f47f387.png)

The complete report can be found here https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fblaze.now.sh%2F#accessibility

**Comment by blenderskool** [comment]
Also, the `alt` attribute for `img` tag here could be "Powered by DigitalOcean" and the link label can be set as "DigitalOcean"

**Comment by dipanshubhola1009** [comment]
I m interested.

**Comment by dipanshubhola1009** [comment]
I have fixed this issue and thanks in advance for merge.

**Comment by blenderskool** [comment]
This issue is still open in case anyone is interested to work as there haven't been any updates from @dipanshubhola1009 in their PR from the review.

**Comment by RotonEvan** [comment]
#86 I've fixed the issue and submitted a pull request

**Comment by RotonEvan** [comment]
> #86 I've fixed the issue and submitted a pull request

@blenderskool please verify the changes :)
