### ISSUE TITLE
Fix social link preview images

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#89]
There is some issue with loading the preview images when a link to Blaze is shared on social media. The image is available at the path `client/src/assets/images/site-preview.jpg` and `<meta>` tags referencing these images are present in `client/src/template.html` but due to some bug, the images don't show up in social preview.

Example on Facebook:
![](https://user-images.githubusercontent.com/21107799/97087856-c1381080-164a-11eb-9293-de5ec941a18a.png)

_Tested on https://socialsharepreview.com/?url=https://blaze.now.sh/_

**Comment by SreejithNS** [comment]
Please refer Pull Request #92
