### ISSUE TITLE
Refactor tested browsers list to use CSS grid

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#90]
Tested browsers list may get wrapped weirdly on different screen sizes. We can refactor it to CSS grid to prevent this. This can be of help to anyone who picks this up: https://css-tricks.com/auto-sizing-columns-css-grid-auto-fill-vs-auto-fit/

### Current Behavior

![](https://user-images.githubusercontent.com/21107799/97088257-48868380-164d-11eb-8f69-e766dc6a31b3.png)

**Comment by khamer** [comment]
@blenderskool are you looking for a solution without a breakpoint? Or doesn't matter?

**Comment by blenderskool** [comment]
@khamer Preferably not a breakpoint, I think it's easy to achieve it with CSS Grid and auto fill referenced in the link

**Comment by RedLinus** [comment]
How do you want it to be fixed?
Do you want it to go from this:
![image](https://user-images.githubusercontent.com/55694176/97091583-26850500-163d-11eb-9e79-480dc7d7d620.png)

Directly to this:
![image](https://user-images.githubusercontent.com/55694176/97091589-31d83080-163d-11eb-8ac6-2777a08bc332.png)
?
I can take this on anyway, just want tot know how you want it 🙂

**Comment by blenderskool** [comment]
@RedLinus yeah that's the expected behaviour. It is either a 2*2 grid or 4*1 when there's no space for 2*2 grid.
