### ISSUE TITLE
Fix Try in PWD button

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#91]
`Try in PWD` (Play with Docker) button is broken since Blaze v2.0.0 update. It needs to be fixed by adding a separate configuration file.
A good repository for some reference is https://github.com/vegasbrianc/prometheus
Also, check out the `docker-compose` file to learn more about how the project is structured in terms of Docker images.

**Comment by minaorangina** [comment]
I've raised a PR for this :)

**Comment by blenderskool** [comment]
Try in PWD button is no longer shown from the README, closing this now
