### ISSUE TITLE
Escape key to close Modals

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#94]
Modal components should close when `Escape` key is pressed on the keyboard.

**Comment by sooster910** [comment]
Hi @blenderskool  👋  . Can I try to work on this?

**Comment by blenderskool** [comment]
Sure @sooster910 🙂

**Comment by talhaabbasi** [comment]
Hi, can I work on this?

**Comment by blenderskool** [comment]
@talhaabbasi maybe @sooster910 is already working on this
