### ISSUE TITLE
Highlight active link in header

### ISSUE THREAD

**Issue by blenderskool** [blenderskool/blaze#98]
The active page currently open is not highlighted in the header. A basic indicator for the same can be added following the below design.

![image](https://user-images.githubusercontent.com/21107799/101775031-e7d7db00-3b14-11eb-97ee-c262201a5dec.png)

**Comment by hashkazi00** [comment]
Can I take this up @blenderskool ? I want to contribute to open source as a beginner.

**Comment by blenderskool** [comment]
@hashkazi00 Sure, go ahead! Let me know if you face some problems in this.

**Comment by hashkazi00** [comment]
![Screenshot 2021-01-06 at 12 59 11 AM](https://user-images.githubusercontent.com/37013706/103690229-67dd4d80-4fba-11eb-9f0a-435d6f4de796.png)

Does this look good to you?

**Comment by blenderskool** [comment]
@hashkazi00 The style looks very similar to the hover style. Would prefer the dot below the link.

**Comment by hashkazi00** [comment]
Absolutely, onto it.
